version: '3'

services:
  api:
    # Build dockerfile
    build:
      context: .
      dockerfile: Dockerfile
    # Restart container in case of crashes etc
    restart: always
    # Set API to use host networking
    # network_mode: host # for not mac
    network_mode: bridge
    ports:
      - 3333:3333
    # API depends on DB to be there
    # depends_on:
    #   - db
    # Set env variables
    environment:
      APP_KEY: "${APP_KEY}"
      CACHE_VIEWS: "${CACHE_VIEWS}"
      SESSION_DRIVER: "${SESSION_DRIVER}"
      TZ: "${TZ}"
      DRIVE_DISK: "${DRIVE_DISK}"
      DB_CONNECTION: "${DB_CONNECTION}"
      PG_HOST: host.docker.internal
      PG_PORT: "${PG_PORT}"
      PG_USER: "${PG_USER}"
      PG_PASSWORD: "${PG_PASSWORD}"
      PG_DB_NAME: "${PG_DB_NAME}"

    volumes:
      - uploads:/home/node/app/public/uploads

volumes:
  uploads: